import {StyleSheet} from 'react-native';

const styles =  StyleSheet.create({
    container:{
        justifyContent:"space-around",
        alignItems:"center",
        flex:1.5,
    },
    subtitle:{
        fontFamily:"Nunito-Semibold",
        fontSize:16,
        letterSpacing:.15,
        color:"white",
        flex:.5,
    },  
    overline:{
        fontFamily:"Nunito-Regular",
        fontSize:10,
        letterSpacing:1.5,
        color:"white",
        marginLeft:10,
    },
    heading4:{
        fontFamily:"Nunito-Semibold",
        fontSize:34,
        letterSpacing:.25,
        color:"white",
    },
    heading6:{
        fontFamily:"Nunito-Semibold",
        fontSize:20,
        letterSpacing:.15,
        color:"white",
        marginLeft:10,
        marginTop:15,
    },
    inputCont:{
        width:'100%', 
        marginVertical:'2%',
        height:60,
        justifyContent:'center',
        paddingHorizontal:20
        
    },
    input:{
        width:250,
        height: 45,
        borderRadius:5,
        margin:8,
        backgroundColor:"rgba(255,255,255,.3)",
        padding:15,
        fontFamily:"Nunito-Regular",        
    },
    inputFocus:{
        color:"#FFD96F",
    },
    icon:{
        margin:10,
        color: "#07191E",
        backgroundColor:"#FFD96F",
        borderRadius:5
    },
    menu:{
        flexDirection:"row",
    },
    nav:{
        justifyContent:"center",
        alignItems:"center",
        flex:1,
        position:"absolute",
        top:10
    },
    screen:{
        flex:2,
        justifyContent:"center",
        alignItems:"flex-start",
        marginTop:20,
    },
    day:{
        flexDirection:"row",
    },
    img:{
        width:170,
        height:100,
        resizeMode:'contain',
        margin:10
    },
    imgRow:{
        flexDirection:"row",
    },
    infoForm:{
        flex:2
    },
    label:{
        fontFamily:"Nunito-Regular",
        color:"white",
    }
})

export default styles;
