import {StyleSheet} from 'react-native';

const style = StyleSheet.create({
    container:{
        backgroundColor:"#152227",
        width:350,
        height:175,
        borderRadius:10,
        marginVertical:5
    },
    position:{
        justifyContent:"center",
        alignItems:"center",
        marginTop:10
    },
    favTitle:{
        fontSize:24,
        marginLeft:10,
        marginTop:10,
        paddingHorizontal:5,
        color:"white"
    },
    favDescr:{
        fontSize:14,
        marginLeft:12,
        paddingHorizontal:5,
        paddingBottom:10,
        color:"white"
    },
    img:{
        width:175,
        height:100,
        backgroundColor:'red',
        borderTopLeftRadius:10
    },
    img2:{
        width:175,
        height:100,
        backgroundColor:'blue',
        borderTopRightRadius:10
    },
    imgPosition:{
        flexDirection:"row"
    },
    favImg:{
        position:'absolute',
        right:0,
        bottom:0,
        flexDirection:'row',
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"white",
        borderRadius:20,
        width:40,
        height:40,
        marginRight:12,
        marginBottom:12
    }
})

export default style;