import {StyleSheet} from 'react-native';

var styles = StyleSheet.create({
    container:{
        flex:10.5
    },
    searchContainer:{
        alignItems:'center',
        justifyContent:'center',
        elevation:20,
        padding:10,
        paddingVertical:20,
        flexDirection:'row',
        position:'absolute',
        right:0,
        left:0,
        backgroundColor:'#061A20'
    },
    searchBar:{
        backgroundColor:'white',
        width:'95%',
        height:35,
        borderRadius:7,
        paddingHorizontal:40,
        borderWidth:0.5
    },
    FGcontainer:{
        backgroundColor:"#417a4f",
        borderRadius:25,
        position:'absolute',
        right:25,
        padding:3,
        paddingHorizontal:15
    },
    FRcontainer:{
        backgroundColor:"#cb3a00",
        borderRadius:25,
        position:'absolute',
        right:25,
        padding:3,
        paddingHorizontal:15
    },
    Ftext:{
        color:'white'
    },
    buttonContainer:{
        flexDirection:'row',
        position:'absolute',
        justifyContent:'center',
        left:0,
        right:0,
        elevation:5,
        marginTop:80
    },
    button:{
        flexDirection:'row',
        alignItems:'center',
        padding:8,
        paddingHorizontal:28,
        elevation:10,
        zIndex:20

    },
    buttontxt:{
        fontSize:15,
        letterSpacing:1,
        fontFamily:"Nunito-Regular",        
    },
    map:{
        width:'100%',
        height:'100%',
        zIndex:-10,
        elevation:-10
    },
    calloutView:{
        backgroundColor:'white',
        position:'absolute',
        top:-350
    }
})

export default styles;